// Code generated by ent, DO NOT EDIT.

package blog

const (
	// Label holds the string label denoting the blog type in the database.
	Label = "blog"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldPhonenumber holds the string denoting the phonenumber field in the database.
	FieldPhonenumber = "phonenumber"
	// FieldBlogcontent holds the string denoting the blogcontent field in the database.
	FieldBlogcontent = "blogcontent"
	// FieldGithublink holds the string denoting the githublink field in the database.
	FieldGithublink = "githublink"
	// Table holds the table name of the blog in the database.
	Table = "blogs"
)

// Columns holds all SQL columns for blog fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldTitle,
	FieldEmail,
	FieldPhonenumber,
	FieldBlogcontent,
	FieldGithublink,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// BlogcontentValidator is a validator for the "Blogcontent" field. It is called by the builders before save.
	BlogcontentValidator func(string) error
)
